# Add task
# $kubectl apply -f crda-report.yaml -n tekton-pipelines
# Start the task
#$ tkn task start --showlog -n tekton-pipelines crda-report

apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: crda-report

spec:
  steps:
    - name: crda-report
      image: quay.io/jparsai/crdaimagev1:latest
      command: ['/bin/bash', '-c']
      args:
        - say_hello
        #- pwd
